name: mapbox_gl_dart
version: 0.1.5
description: Mapbox-gl wrapper for Dart. Library to use Mapbox GL JS in your web Dart projects.
homepage: https://github.com/andrea689/mapbox-gl-dart/
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  js: ^0.6.1
  meta: ^1.1.8

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.0.0 <3.0.0"
